services:
    open-archiver:
        image: logiclabshq/open-archiver:v0.5.0
        container_name: open-archiver
        restart: unless-stopped
        ports:
            - '4000:4000'
            - '4001:3000'
        env_file:
            - .env
        volumes:
            - ${OMV_DIR}/openarchiver/archiver-data:/var/data/open-archiver
        depends_on:
            - postgres
            - valkey
            - meilisearch
        networks:
            - open-archiver-net

    postgres:
        image: postgres:17-alpine
        container_name: open-archiver-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ${DATA_DIR}/openarchiver/pgdata:/var/lib/postgresql/data
        networks:
            - open-archiver-net

    valkey:
        image: valkey/valkey:8-alpine
        container_name: open-archiver-valkey
        restart: unless-stopped
        command: valkey-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ${DATA_DIR}/openarchiver/valkeydata:/data
        networks:
            - open-archiver-net

    meilisearch:
        image: getmeili/meilisearch:v1.38
        container_name: open-archiver-meilisearch
        restart: unless-stopped
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
        volumes:
            - ${OMV_DIR}/openarchiver/meilidata:/meili_data
        networks:
            - open-archiver-net

networks:
    open-archiver-net:
        driver: bridge
