services:
  app:
    image: ghcr.io/hargata/lubelogger:v1.6.4
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - ${DATA_DIR}/lubelogger/lubelogger_data:/App/data
      - ${DATA_DIR}/lubelogger/lubelogger_keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8158:8080
    env_file:
      - .env