services:
  grafana:
    image: grafana/grafana-oss:13.0.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_volume:/var/lib/grafana

  loki:
    image: grafana/loki:3.7.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.6.10
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

volumes:
  grafana_volume:
    external: true