services:
    uptime-kuma:
        image: 'louislam/uptime-kuma:2.2.1'
        container_name: uptime-kuma
        volumes:
            - '${DATA_DIR}/uptime-kuma:/app/data'
        ports:
            - '3001:3001'
        restart: always
