services:
  foundry:
    image: felddy/foundryvtt:14.359.0
    hostname: my_foundry_host
    volumes:
      - ${DATA_DIR}/foundryvtt/foundrydata:/data
    env_file:
      - .env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser:v2.63.1
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - ${DATA_DIR}/foundryvtt/foundrydata:/data
      - ${DATA_DIR}/foundryvtt/fileserver-config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always