services:
  app:
    image: 'jc21/nginx-proxy-manager:2.14.0'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${DATA_DIR}/nginx-proxy-manager/npm_data:/data
      - ${DATA_DIR}/nginx-proxy-manager/npm_letsencrypt:/etc/letsencrypt