services:
    photon:
        image: rtuszik/photon-docker:2.1.1
        env_file: .env
        volumes:
            - /omv/docker-volumes/photon-data:/photon/data
        restart: unless-stopped
        ports:
            - "2322:2322"
