services:
  actual_server:
    image: docker.io/actualbudget/actual-server:26.5.2
    ports:
      - '5006:5006'
    volumes:
      - ${DATA_DIR}/actual-budget:/data
    restart: unless-stopped

  actual-helpers:
    container_name: actual-helpers
    image: ghcr.io/psybers/actual-helpers:latest@sha256:c253e00a107ef765273c650600b784878f0c765ddcc68fc98d276335d8fbbfdc
    env_file: .env
    volumes:
      - ${DATA_DIR}/actual-helpers/actual-cache:/usr/src/app/cache
    restart: unless-stopped

  actualtap-py:
    container_name: actualtap-py
    image: ghcr.io/bobokun/actualtap-py:v0.1.9
    ports:
      - 15482:8000
    volumes:
      - ${DATA_DIR}/actual-tap:/config
    restart: unless-stopped