services:
  actual_server:
    image: docker.io/actualbudget/actual-server:26.5.2
    ports:
      - '5006:5006'
    volumes:
      - ${DATA_DIR}/actual-budget:/data
    restart: unless-stopped

  actual-helpers:
    container_name: actual-helpers
    image: ghcr.io/psybers/actual-helpers:latest@sha256:90d94e765a98087441d5e0822d215c043014f301aabd69400e4070c7c312828c
    env_file: .env
    volumes:
      - ${DATA_DIR}/actual-helpers/actual-cache:/usr/src/app/cache
    restart: unless-stopped

  actualtap-py:
    container_name: actualtap-py
    image: ghcr.io/bobokun/actualtap-py:v0.1.9
    ports:
      - 15482:8000
    volumes:
      - ${DATA_DIR}/actual-tap:/config
    restart: unless-stopped