services:
  actual_server:
    image: docker.io/actualbudget/actual-server:edge@sha256:f66f61ff688ca4e7c954285def2c1c4688e6891767d6d038f715f8fe15fc3b02
    ports:
      - '5006:5006'
    volumes:
      - ${DATA_DIR}/actual-budget:/data
    restart: unless-stopped

  actual-helpers:
    container_name: actual-helpers
    image: ghcr.io/psybers/actual-helpers:latest@sha256:fbed67fce610b92dc2a74832a2398a9bbc003b10b17d9816bc929fe184d04733
    env_file: .env
    volumes:
      - ${DATA_DIR}/actual-helpers/actual-cache:/usr/src/app/cache
    restart: unless-stopped

  actualtap-py:
    container_name: actualtap-py
    build:
      context: ./actualtap
    ports:
      - 15482:8000
    volumes:
      - ${DATA_DIR}/actual-tap:/config
    restart: unless-stopped
